### ISSUE TITLE
I can't watch the videos

### ISSUE THREAD

**Issue by 1033020837** [simoninithomas/Deep_reinforcement_learning_Course#15]
Hello, I am a student in China and I am trying to watch your videos about reinforcement learning, but when I click the address of the video, I got a error which show it's an unvalid address. Can you help me?

**Comment by simoninithomas** [comment]
Hi,
What link did you clicked?
I'm afraid it's because Youtube is forbidden in China.

**Comment by 1033020837** [comment]
Thanks for your response. I am using a vpn so Youtube is available for me.
Any "Read the article" button in this page "https://simoninithomas.github.io/Deep_reinforcement_learning_Course/"  is unavailable for me.
For instance, the article about Q-Learning which address is "https://medium.freecodecamp.org/diving-deeper-into-reinforcement-learning-with-q-learning-c18d0db58efe".

**Comment by simoninithomas** [comment]
I've just tested them, all links are working that's strange.
Maybe Medium blog is blocked too even with a VPN?
Let's try something, if I create a bit.ly link can you see the article about Q-learning http://bit.ly/2Nwvek1 ?

**Comment by 1033020837** [comment]
I can view this page,but it seems some picture and css resourse are unavailable so the page looks just like this:
![3py2iyhgq ax ih82](https://user-images.githubusercontent.com/26853321/45943972-1132ec00-c01b-11e8-980e-112e925895e6.png)

**Comment by simoninithomas** [comment]
Ok so I think it comes from the fact that Medium is blocked. That's a shame 😢. 
Two solutions:
If the pictures of the articles are present, you can read the article like that (sure it's ugly but it can do the work)
Or Maybe use another VPN. I heard about https://shadowsocks.org/en/index.html a lot of people that worked in China use this.

**Comment by simoninithomas** [comment]
I sent you Q-learning article copy,
Hope it helps
