### ISSUE TITLE
PPO the agent is not trained yet?

### ISSUE THREAD

**Issue by Silence1995** [simoninithomas/Deep_reinforcement_learning_Course#25]
When I visited the  [link](https://github.com/simoninithomas/Deep_reinforcement_learning_Course/tree/master/PPO%20with%20Sonic%20the%20Hedgehog)
I found the words below "WORK IN PROGRESS: the agent is not trained yet ⚠️⚠️⚠️⚠️".
Does it mean that agent.py is not complete? Or there is no well trained model?

**Comment by simoninithomas** [comment]
Hi, sorry for the delayed response,
The agent is complete but not trained, I'm currently updating all the implementations but it takes time.
Have a great day

**Comment by kmcnayr** [comment]
What is the status of this? I'm not getting very good results after training for ~20 hours. Can anyone share their model checkpoint? I would like to see a good model in action.
