### ISSUE TITLE
 Game not found

### ISSUE THREAD

**Issue by Silence1995** [simoninithomas/Deep_reinforcement_learning_Course#30]
When i try to run the sample code of Deep Q Learning DQN Atari Space Invaders.ipynb
I got the error message like Game not found: SpaceInvaders-Atari2600.
where can i download the SpaceInvaders-Atari2600 ROM file
thank you

**Comment by simoninithomas** [comment]
Hi,
You need to download the SpaceInvaders-Atari2600 Rom on the internet
In fact games with retro are not provided.
Then you just need to go to your download folder and type retro import . (don't forget the dot).

Have a nice day,
