### ISSUE TITLE
retro has no attribute make

### ISSUE THREAD

**Issue by HsnAtwi** [simoninithomas/Deep_reinforcement_learning_Course#36]
I'm getting a weird error when I'm running the deep Q learning space invaders example

"   env = retro.make(game ='SpaceInvaders-Atari2600')
AttributeError: module 'retro' has no attribute 'make'
"
I installed the gym-retro and have python 3.6 working on windows 10
but I'm still new to this

**Comment by simoninithomas** [comment]
Hi,

That's strange. Sometimes it's because you called and import a file called retro.py and this create confusion.

**Comment by simoninithomas** [comment]
Do you still have this issue ?

**Comment by HsnAtwi** [comment]
Yes I still have it, yeah at first I installed the wrong library(which gave me different kind of error), but then I uninstalled it and installed the gym-retro instead.

**Comment by BlkPingu** [comment]
@HsnAtwi could you tell us how you debugged it? I'm having the same issue and there is no documented fix yet

**Comment by abhinavchawla13** [comment]
I had the same issue. 
I resolved it by:
`pip uninstall retro` and then `pip install gym-retro` 
Apparently, **retro** is another package, so we need to specifically install **gym-retro**.
