### ISSUE TITLE
rewards_list variable in Deep Q Learning in Space Invaders

### ISSUE THREAD

**Issue by crazylazylife** [simoninithomas/Deep_reinforcement_learning_Course#71]
The rewards_list variable used in the training of the agent for the game of Space Invaders with Deep Q Network is not defined before. I did not find any other application of the variable other than where the episode and the total reward in each episode is being appended. Do we actually need it or we can ignore it for this case.

**Comment by samiulextreem** [comment]
yes you are right.just erase the line

**Comment by crazylazylife** [comment]
Closing the issue. Now that its confirmed that the code is not affected.
