### ISSUE TITLE
Requirements .txt needed

### ISSUE THREAD

**Issue by piEsposito** [simoninithomas/Deep_reinforcement_learning_Course#73]
I would like to know the exact environment you're using, as sometimes, due to lib versions, it does not run. Also, thank you for the awesome course!

**Comment by whgreate** [comment]
it's mine , seems work fine (python3.6):

gym==0.10.9
tensorboardX==1.6
tensorflow==1.12.0
tensorboard==1.12.0

**Comment by sevenseablue** [comment]
mine is all latest
